In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('C:\\Users\\INFINIX\\Vistara-Innoverse\\ml\\verification\\properties_with_verification.csv')
df.head()

,property_id,property_name,city,property_type,max_guests,bedrooms,beds,bathrooms,living_room,kitchen,...,smoke_alarm,carbon_monoxide_alarm,step_free_access,accessible_parking,wide_guest_entry,step_free_bedroom,step_free_bathroom,host_languages,verification_score,verification_status
0,VST001,Urban Comfort Home 001,Delhi,Entire Home,6,4,5,2,1,1,...,1,1,0,0,0,0,0,"English,Hindi",1.0,Verified
1,VST002,Green Garden Home 002,Mumbai,Apartment,6,3,5,2,1,1,...,1,1,0,0,0,0,0,"English,Hindi,Bengali",1.0,Verified
2,VST003,City View Home 003,Bengaluru,Villa,3,2,2,1,1,1,...,1,1,0,0,0,0,0,"English,Hindi,Marathi",1.0,Verified
3,VST004,Family Stay Home 004,Jaipur,Homestay,3,1,2,1,1,1,...,1,1,0,0,0,0,0,"English,Hindi,Tamil",1.0,Verified
4,VST005,Lake View Home 005,Goa,Studio,7,4,6,2,0,0,...,1,1,0,0,0,0,0,"English,Hindi,Telugu",1.0,Verified

In [8]:
df.shape

(100, 60)

In [9]:
df.columns

Index(['property_id', 'property_name', 'city', 'property_type', 'max_guests',
       'bedrooms', 'beds', 'bathrooms', 'living_room', 'kitchen', 'balcony',
       'terrace', 'ac', 'wifi', 'parking', 'pool', 'tv', 'workspace',
       'washing_machine', 'fridge', 'microwave', 'power_backup',
       'price_per_night', 'price_3hr', 'price_6hr', 'price_9hr',
       'cleaning_fee', 'service_fee_percent', 'estimated_total_1_night',
       'estimated_total_3hr', 'estimated_total_6hr', 'estimated_total_9hr',
       'rating', 'review_count', 'verified', 'available', 'available_from',
       'available_to', 'hairdryer', 'heating', 'iron', 'hot_tub', 'ev_charger',
       'breakfast', 'gym', 'bbq_grill', 'self_check_in', 'instant_book',
       'free_cancellation', 'allows_pets', 'smoke_alarm',
       'carbon_monoxide_alarm', 'step_free_access', 'accessible_parking',
       'wide_guest_entry', 'step_free_bedroom', 'step_free_bathroom',
       'host_languages', 'verification_score', 'verification_status'],
      dtype='object')

In [10]:
df.dtypes

property_id                 object
property_name               object
city                        object
property_type               object
max_guests                   int64
bedrooms                     int64
beds                         int64
bathrooms                    int64
living_room                  int64
kitchen                      int64
balcony                      int64
terrace                      int64
ac                           int64
wifi                         int64
parking                      int64
pool                         int64
tv                           int64
workspace                    int64
washing_machine              int64
fridge                       int64
microwave                    int64
power_backup                 int64
price_per_night              int64
price_3hr                    int64
price_6hr                    int64
price_9hr                    int64
cleaning_fee                 int64
service_fee_percent          int64
estimated_total_1_night      int64
estimated_total_3hr          int64
estimated_total_6hr          int64
estimated_total_9hr          int64
rating                     float64
review_count                 int64
verified                     int64
available                    int64
available_from              object
available_to                object
hairdryer                    int64
heating                      int64
iron                         int64
hot_tub                      int64
ev_charger                   int64
breakfast                    int64
gym                          int64
bbq_grill                    int64
self_check_in                int64
instant_book                 int64
free_cancellation            int64
allows_pets                  int64
smoke_alarm                  int64
carbon_monoxide_alarm        int64
step_free_access             int64
accessible_parking           int64
wide_guest_entry             int64
step_free_bedroom            int64
step_free_bathroom           int64
host_languages              object
verification_score         float64
verification_status         object
dtype: object

In [11]:
df.isnull().sum()

property_id                0
property_name              0
city                       0
property_type              0
max_guests                 0
bedrooms                   0
beds                       0
bathrooms                  0
living_room                0
kitchen                    0
balcony                    0
terrace                    0
ac                         0
wifi                       0
parking                    0
pool                       0
tv                         0
workspace                  0
washing_machine            0
fridge                     0
microwave                  0
power_backup               0
price_per_night            0
price_3hr                  0
price_6hr                  0
price_9hr                  0
cleaning_fee               0
service_fee_percent        0
estimated_total_1_night    0
estimated_total_3hr        0
estimated_total_6hr        0
estimated_total_9hr        0
rating                     0
review_count               0
verified                   0
available                  0
available_from             0
available_to               0
hairdryer                  0
heating                    0
iron                       0
hot_tub                    0
ev_charger                 0
breakfast                  0
gym                        0
bbq_grill                  0
self_check_in              0
instant_book               0
free_cancellation          0
allows_pets                0
smoke_alarm                0
carbon_monoxide_alarm      0
step_free_access           0
accessible_parking         0
wide_guest_entry           0
step_free_bedroom          0
step_free_bathroom         0
host_languages             0
verification_score         0
verification_status        0
dtype: int64

In [12]:
df['city'].unique()

array(['Delhi', 'Mumbai', 'Bengaluru', 'Jaipur', 'Goa', 'Varanasi',
       'Manali', 'Hyderabad', 'Kolkata', 'Agra', 'Udaipur', 'Pune',
       'Chennai', 'Rishikesh', 'Ayodhya', 'Amritsar', 'Shimla', 'Jodhpur',
       'Kochi', 'Mysuru'], dtype=object)

In [13]:
df['price_per_night'].describe()

count     100.000000
mean     3695.000000
std      1103.930078
min      2000.000000
25%      2700.000000
50%      3500.000000
75%      4600.000000
max      5600.000000
Name: price_per_night, dtype: float64

In [14]:
property = df.iloc[0]

In [15]:
# Recommendatiton
user = {
    "city": "Delhi",
    "budget": 5000,
    "guests": 2,
    "bedroom": 4,
    "bathrooms": 1,

    "property_type": "Entire Home",

    "kitchen": 1,
    "wifi": 1,
    "parking": 1,
    "ac": 1,
    "balcony": 1,
    "terrace": 0,
    "workspace": 1,
    "pool": 0,
    "washing_machine": 1,

    "self_check_in": 1,
    "free_cancellation": 1,
    "allows_pets": 0,
    "check_in": "2026-11-01",
    "check_out": "2026-11-03"
}

In [ ]:
filters = {
    "property_type": user["property_type"],
    "bedrooms": user["bedroom"],
    "bathrooms": user["bathrooms"],
    "kitchen": user["kitchen"],
    "wifi": user["wifi"],
    "parking": user["parking"],
    "ac": user["ac"],
    "balcony": user["balcony"],
    "self_check_in": user["self_check_in"]
}

In [18]:
filtered_df = df[
    (df["city"] == user["city"]) &
    (df["max_guests"] >= user["guests"]) &
    (df["available"] == 1) &
    (pd.to_datetime(df["available_from"]) <= user["check_in"]) &
    (pd.to_datetime(df["available_to"]) >= user["check_out"])
].copy()

In [31]:
filtered_df = filtered_df[
    (filtered_df["property_type"] == user["property_type"]) &
    (filtered_df["bedrooms"] >= user["bedroom"]) &
    (filtered_df["bathrooms"] >= user["bathrooms"]) &
    (filtered_df["kitchen"] >= user["kitchen"]) &
    (filtered_df["wifi"] >= user["wifi"]) &
    (filtered_df["parking"] >= user["parking"]) &
    (filtered_df["ac"] >= user["ac"]) &
    (filtered_df["balcony"] >= user["balcony"]) &
    (filtered_df["self_check_in"] >= user["self_check_in"])
].copy()

In [32]:
filtered_df.shape

(3, 61)

In [20]:
df[df["city"] == "Delhi"][["property_id", "price_per_night", "bedrooms", "bathrooms"]]

   property_id  price_per_night  bedrooms  bathrooms
0       VST001             4600         4          2
20      VST021             4600         4          2
40      VST041             4500         4          2
60      VST061             5200         4          2
80      VST081             5100         4          2

In [21]:
def calculate_score(property):

    #For Location Score
    if user["city"] == property["city"]:
        location_score = 0.20
    else:
        location_score = 0

    #For Budget Score
    price_difference = abs(user["budget"] - property["price_per_night"])
    budget_match = 1 - (price_difference / user["budget"])
    budget_score = max(0, budget_match) * 0.20

    #For Bedroom Score 
    if property["bedrooms"] >= user["bedroom"]:
        bedroom_score = 0.12
    else:
        bedroom_score = 0
        
    #Fo Bathroom Score
    if property["bathrooms"] >= user["bathrooms"]:
        bathroom_score = 0.08
    else:
        bathroom_score = 0


    #For Amenities Score
    amenities_score = 0

    if user["kitchen"] == 1 and property["kitchen"] == 1:
        amenities_score += 0.0375

    if user["wifi"] == 1 and property["wifi"] == 1:
        amenities_score += 0.025

    if user["parking"] == 1 and property["parking"] == 1:
        amenities_score += 0.075

    if user["ac"] == 1 and property["ac"] == 1:
        amenities_score += 0.0125


    #For Rating Score
    rating_score = (property["rating"] / 5) * 0.07
    max_reviews = df["review_count"].max()
    review_score = (property["review_count"] / max_reviews) * 0.03

    #For Verified Scoe
    if property["available"] == 1:
        availability_score = 0.05
    else:
        availability_score = 0

    if property["verified"] == 1:
        verified_score = 0.05
    else:
        verified_score = 0

    #For Preferences Score
    preferences = ["balcony", "terrace", "workspace","pool", "washing_machine"]

    matched_preferences = 0
    selected_preferences = 0

    for feature in preferences:
        if user[feature] == 1:
            selected_preferences += 1
            if property[feature] == 1:
                matched_preferences += 1

    preference_score = (
        matched_preferences / selected_preferences * 0.05
        if selected_preferences > 0 else 0
    )

    final_score = (
        location_score
        + budget_score
        + bedroom_score
        + bathroom_score
        + amenities_score
        + rating_score
        + review_score
        + availability_score
        + verified_score
        + preference_score
    )

    return final_score

In [33]:
filtered_df["final_score"] = filtered_df.apply(calculate_score, axis=1)

In [38]:
recommendations = filtered_df.sort_values("final_score",ascending=False)

In [40]:
recommendations[["property_id",
                "property_name",
                "city",
                "property_type",
                "max_guests",
                "bedrooms",
                "beds",
                "bathrooms",
                "price_per_night",
                "price_3hr",
                "price_6hr",
                "price_9hr",
                "rating",
                "review_count",
                "verified",
                "self_check_in",
                "kitchen",
                "wifi",
                "parking",
                "ac",
                "balcony",
                "final_score",
                "verification_score",
                "verification_status"
]].head(10)

,property_id,property_name,city,property_type,max_guests,bedrooms,beds,bathrooms,price_per_night,price_3hr,...,verified,self_check_in,kitchen,wifi,parking,ac,balcony,final_score,verification_score,verification_status
60,VST061,Urban Comfort House 061,Delhi,Entire Home,6,4,5,2,5200,1450,...,1,1,1,1,1,1,1,0.968055,1.0,Verified
0,VST001,Urban Comfort Home 001,Delhi,Entire Home,6,4,5,2,4600,1300,...,1,1,1,1,1,1,1,0.955463,1.0,Verified
40,VST041,Urban Comfort Residence 041,Delhi,Entire Home,7,4,6,2,4500,1250,...,1,1,1,1,1,1,1,0.954524,1.0,Verified

In [35]:
top_property = recommendations.iloc[0]

reasons = []

if top_property["city"] == user["city"]:
    reasons.append("Preferred location")

if top_property["price_per_night"] <= user["budget"]:
    reasons.append("Within your budget")
else:
    reasons.append("Above your budget")

if top_property["bedrooms"] >= user["bedroom"]:
    reasons.append("Bedroom requirement matched")

if top_property["bathrooms"] >= user["bathrooms"]:
    reasons.append("Bathroom requirement matched")

if top_property["kitchen"] == 1 and user["kitchen"] == 1:
    reasons.append("Kitchen available")

if top_property["wifi"] == 1 and user["wifi"] == 1:
    reasons.append("Wi-Fi available")

if top_property["parking"] == 1 and user["parking"] == 1:
    reasons.append("Free parking available")

if top_property["ac"] == 1 and user["ac"] == 1:
    reasons.append("Air conditioning available")

if top_property["rating"] >= 4.5:
    reasons.append("Highly rated")

if top_property["review_count"] >= 50:
    reasons.append("Many guest reviews")

if top_property["verified"] == 1:
    reasons.append("Verified property")

In [36]:
print(reasons)

['Preferred location', 'Above your budget', 'Bedroom requirement matched', 'Bathroom requirement matched', 'Kitchen available', 'Wi-Fi available', 'Free parking available', 'Air conditioning available', 'Highly rated', 'Many guest reviews', 'Verified property']

In [37]:
print("Property:", top_property["property_name"])
print("Match Score:", round(top_property["final_score"] * 100, 2))
print("Why this stay:")
for reason in reasons:
    print("✓", reason)

Property: Urban Comfort House 061
Match Score: 96.81
Why this stay:
✓ Preferred location
✓ Above your budget
✓ Bedroom requirement matched
✓ Bathroom requirement matched
✓ Kitchen available
✓ Wi-Fi available
✓ Free parking available
✓ Air conditioning available
✓ Highly rated
✓ Many guest reviews
✓ Verified property